CREATE TABLE IF NOT EXISTS `#__pungaanalytics_events` (
	`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`visited_at` DATETIME NOT NULL,
	`visit_date` DATE NOT NULL,
	`visitor_hash` CHAR(32) NOT NULL,
	`path` VARCHAR(1024) NOT NULL,
	`component` VARCHAR(100) NOT NULL DEFAULT '',
	`view_name` VARCHAR(100) NOT NULL DEFAULT '',
	`referrer_host` VARCHAR(255) NOT NULL DEFAULT '',
	`country_code` CHAR(2) NOT NULL DEFAULT 'ZZ',
	`language_code` VARCHAR(16) NOT NULL DEFAULT '',
	`device_type` VARCHAR(16) NOT NULL DEFAULT 'unknown',
	`browser_family` VARCHAR(32) NOT NULL DEFAULT 'Other',
	`is_bot` TINYINT(1) NOT NULL DEFAULT 0,
	`bot_name` VARCHAR(64) NOT NULL DEFAULT '',
	`event_type` VARCHAR(16) NOT NULL DEFAULT 'pageview',
	PRIMARY KEY (`id`),
	KEY `idx_pungaanalytics_visited_at` (`visited_at`),
	KEY `idx_pungaanalytics_visit_date` (`visit_date`),
	KEY `idx_pungaanalytics_visitor_hash` (`visitor_hash`),
	KEY `idx_pungaanalytics_bot_date` (`is_bot`, `visit_date`),
	KEY `idx_pungaanalytics_country_date` (`country_code`, `visit_date`),
	KEY `idx_pungaanalytics_path` (`path`(191)),
	KEY `idx_pungaanalytics_referrer` (`referrer_host`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;
