DROP TABLE IF EXISTS `#__pungaanalytics_page_status`;
DROP TABLE IF EXISTS `#__pungaanalytics_daily_pages`;
DROP TABLE IF EXISTS `#__pungaanalytics_daily_404`;
DROP TABLE IF EXISTS `#__pungaanalytics_daily_items`;
DROP TABLE IF EXISTS `#__pungaanalytics_daily_event_time`;
DROP TABLE IF EXISTS `#__pungaanalytics_daily_time`;
DROP TABLE IF EXISTS `#__pungaanalytics_daily_dimensions`;
DROP TABLE IF EXISTS `#__pungaanalytics_daily`;
DROP TABLE IF EXISTS `#__pungaanalytics_events`;
